kind: Deployment
apiVersion: apps/v1
metadata:
   name: Grami
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: Grami
   template:
      metadata:
        labels:
          app: Grami
      spec:
       containers:
        - name: Grami
          image: ayagrami/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80